--- #YAML:1.0
name:               Amazon-SQS-Simple
version:            1.06
abstract:           OO API for accessing the Amazon Simple Queue 
author:
    - Simon Whitaker <sw@netcetera.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  0
    LWP::UserAgent:     0
    MIME::Base64:       0
    Test::More:         0
    URI::Escape:        0
    XML::Simple:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
