--- #YAML:1.0
name:                Amazon-SQS-Simple
version:             0.6
abstract:            OO API for accessing the Amazon Simple Queue 
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::HMAC_SHA1:             0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    Test::More:                    0
    URI::Escape:                   0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Simon Whitaker <sw@netcetera.org>
