# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Amazon-SQS-Simple
version:      0.4
version_from: lib/Amazon/SQS/Simple.pm
installdirs:  site
requires:
    Digest::HMAC_SHA1:             0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    Test::More:                    0
    URI::Escape:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
